### ISSUE TITLE
Project collaboration

### ISSUE THREAD

**Issue by James4Ever0** [showlab/Awesome-GUI-Agent#16]
I have been working on a computer automating project below. The repo contains my thoughts and model architecture skeletons, even some working prototypes.

The link: https://github.com/james4ever0/agi_computer_control

If you don't mind, you can address my project into the README. If you are interested in my research you can check my [notes](https://github.com/james4ever0/notes).

You can also reach me with email.

**Comment by QinghongLin** [comment]
Hi @James4Ever0 Thanks for your reach out! I will send you email

**Comment by James4Ever0** [comment]
Made one reply to you. It has been a busy week. Check trash/spam folder if not found.

**Comment by James4Ever0** [comment]
Additionally you may find computer control related projects [here](https://github.com/James4Ever0/notes/blob/master/Cybergod-like%20Agents%2C%20General%20Computer%20Control.md) and [here](https://github.com/James4Ever0/notes/blob/master/cybergod%20related%20projects.md).

**Comment by James4Ever0** [comment]
I made some progress over Cybergod. This agent is now fully capable of interacting with terminal in a non-blocking fashion even if the program behind is blocking.

You can see the position of the cursor, the range of the selected text.

![tmux_show_1](https://github.com/user-attachments/assets/25b8567d-837c-44d0-99fb-b221c6ba7244)

You can also capture a screenshot of the terminal with cursor denoted in red.

![vim_edit_tmux_screenshot](https://github.com/user-attachments/assets/15f38a1c-d6eb-48e8-af14-1e16dac79bea)

Grayscale augmented terminal gives high contrast to the red cursor, making the agent easier to locate it.

![grayscale_dark_tmux](https://github.com/user-attachments/assets/570962a2-dc9f-4c3f-82db-796bcfa9ca3d)

**Comment by James4Ever0** [comment]
Additionally I have found a new way to find more computer control agent projects, by first utilizing existing agent benchmark name as Github search query, and then get relevant repositories.
