### ISSUE TITLE
Find more computer agent benchmarks and projects by using LLM agents

### ISSUE THREAD

**Issue by James4Ever0** [showlab/Awesome-GUI-Agent#17]
I have found a new way to find more computer control agent projects, by first utilizing existing agent benchmark names as search queries, and then get relevant repositories.

There are two additional GUI agent projects found in Github using keyword 'OSWorld':

- [OpenAdapt](https://github.com/OpenAdaptAI/OpenAdapt)
- [surfkit](https://github.com/agentsea/surfkit)

Search 'MiniWoB++' in Huggingface Dataset found:

- [Navigating WebAI](https://arxiv.org/html/2405.00516v1)

Computer agent benchmark names usually can be found within papers.

As the list gets longer, it is better to build an LLM agent for it instead of manual searching.

**Comment by h-siyuan** [comment]
The aforementioned projects and paper have been added to the list. We will enhance our collection pipeline to make it more automatic. Thank you!
