### ISSUE TITLE
Add repositories for automated GUI agent and dataset research

### ISSUE THREAD

**Issue by James4Ever0** [showlab/Awesome-GUI-Agent#19]
I have made one such [project](https://github.com/James4Ever0/computer_control_agent_knowledge_base) for this task. It is quite impressive and versatile.

It has the following functionalities:

- Crawl Github README files, papers, links, webpages
- Store and embed text into vector database
- Chat with database (RAG)

It is designed solely for finding latest GUI agent researches.

You can enlist my project, also the automatic pipeline made by your team can also be open-sourced and enlisted, so that more researchers will benefit from it.

https://github.com/showlab/Awesome-GUI-Agent/pull/20

**Comment by QinghongLin** [comment]
@James4Ever0  Thanks for update, I have merged your request. :)
